version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    ports:
      - "9000:9000"
    # volumes:
    #   - ./backend:/app
    environment:
      - DB_URL=${DB_URL}

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
